#!/bin/sh

MKDIR="/bin/mkdir -p"
LN="/bin/ln -s"
RM=/bin/rm

DYNDIRS="/dev/pts"
for DIR in $DYNDIRS ; do
  if [ ! -d $DIR ]; then
    $MKDIR $DIR
  fi
done
for DIR in $($LS var) ; do
   if [ -l $DIR ]; then
    $MKDIR /tmp/$DIR
   fi
done
