gdbm-version:=$(CONFIG_DB_GDBM_VERSION)1.11
subproject-$(CONFIG_DB_GDBM_SP)+=gdbm
gdbm-url:=ftp://ftp.gnu.org/gnu/gdbm/gdbm-$(gdbm-version).tar.gz

sqlite-version:=$(CONFIG_DB_SQLITE_VERSION)
subproject-$(CONFIG_DB_SQLITE_SP)+=sqlite
sqlite-url:=http://www.sqlite.org/2014/sqlite-$(sqlite-version).tar.gz
