
e2fsprogs-version:=$(CONFIG_DISK_EXT2PROGS_VERSION)
subproject-$(CONFIG_DISK_EXT2PROGS_SP)+=e2fsprogs
e2fsprogs-url=http://sourceforge.net/projects/e2fsprogs/files/e2fsprogs/v$(e2fsprogs-version)/e2fsprogs-$(e2fsprogs-version).tar.gz
