subproject-$(CONFIG_MKFS_EXT2)+=e2fsprogs

e2fsprogs-version=$(CONFIG_MKFS_EXT2_VERSION:"%"=%)
e2fsprogs-version=1.42.7
e2fsprogs-url=http://sourceforge.net/projects/e2fsprogs/files/e2fsprogs/v$(e2fsprogs-version)/e2fsprogs-$(e2fsprogs-version).tar.gz
