
zlib-version=$(CONFIG_FW_ZLIB_VERSION)
subproject-$(CONFIG_FW_ZLIB_SP)+=zlib
zlib-url="http://zlib.net/zlib$(zlib-version:%=-%).tar.gz"
libpng-git="https://github.com/madler/zlib.git"
zlib-config=./configure --prefix=/usr --shared
