#!/bin/sh

MKDIR="/bin/mkdir -p"
LN="/bin/ln -s"
LS="/bin/ls"
MOUNT="/bin/mount"
RM="/bin/rm"

$MOUNT /dev 
$MOUNT /proc
$MOUNT /sys
DYNDIRS="/dev/pts /dev/shm"
for DIR in $DYNDIRS ; do
  if [ ! -d $DIR ]; then
    $MKDIR $DIR
  fi
done
$MOUNT -a
for DIR in $($LS /var) ; do
   if [ -L /var/$DIR ]; then
    echo $MKDIR /tmp/var/$DIR
    $MKDIR /tmp/var/$DIR
   fi
done
