#!/bin/sh

MKDIR="/bin/mkdir -p"
CHMOD="/bin/chmod"
LN="/bin/ln -s"
LS="/bin/ls"
MOUNT="/bin/mount"
RM="/bin/rm"

[ ! -n "$1" ] && exit
if [ $1 == start ]; then
$MOUNT /dev 
$MOUNT /proc
$MOUNT /sys
DYNDIRS="/dev/pts /dev/shm"
for DIR in $DYNDIRS ; do
  if [ ! -d $DIR ]; then
    $MKDIR $DIR
  fi
done
$MOUNT -a
for DIR in $($LS /var) ; do
   if [ -L /var/$DIR ]; then
    $MKDIR /tmp/var/$DIR
    $CHMOD 777 /tmp/var/$DIR
   fi
done
fi

