#!/bin/sh

#conf="-f /etc/lighttpd/lighttpd.conf"
#mod="-m /usr/lib/lighttpd"
[ ! -d /var/log/lighttpd ] && mkdir -m 777 /var/log/lighttpd
# lighttpd starts as daemon by default
/usr/sbin/lighttpd $conf $mod 
