#!/bin/sh

. /etc/network/eth0.conf

if [ -e /etc/ushare.conf ]; then
conf="--cfg /etc/ushare.conf"
else
dlna=--dlna
name="--name $hostname"
content="--content /home"
fi
/usr/sbin/ushare $conf $name $content $dlna --daemon
