subproject-$(CONFIG_BOARD_SNOWBALL)+=av8100
av8100-build=make -C $(KDIR) M=$(srctree)/$(src)/av8100 CONFIG_AV8100=m CFLAGS+=-I. modules

DX910-SW-99002-version=r4p0-00rel0
subproject-$(CONFIG_DRIVER_MALI)+=DX910-SW-99002
DX910-SW-99002-url=http://malideveloper.arm.com/downloads/drivers/DX910/$(DX910-SW-99002-version)/DX910-SW-99002-$(DX910-SW-99002-version).tgz

