alsa-version:=1.0.27
alsa-lib-version:=$(alsa-version)
subproject-$(CONFIG_ALSA)=alsa-lib
alsa-lib-url:=ftp://ftp.alsa-project.org/pub/lib/alsa-lib$(alsa-lib-version:%=-%).tar.bz2
alsa-lib-git:=git://git.alsa-project.org/alsa-lib.git 

alsa-utils-version:=$(alsa-version)
subproject-$(CONFIG_ALSA)=alsa-utils
alsa-utils-url:=ftp://ftp.alsa-project.org/pub/utils/alsa-utils$(alsa-utils-version:%=-%).tar.bz2

alsa-tools-version:=$(alsa-version)
subproject-$(CONFIG_ALSA_TOOLS)=alsa-tools
alsa-tools-url:=ftp://ftp.alsa-project.org/pub/tools/alsa-tools$(alsa-tools-version:%=-%).tar.bz2

alsa-plugins-version:=$(alsa-version)
subproject-$(CONFIG_ALSA)=alsa-plugins
alsa-plugins-url:=ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins$(alsa-plugins-version:%=-%).tar.bz2

