
mpd-version:=0.13.2
subproject-$(CONFIG_MM_MPD)+=mpd
mpd-url:=http://www.musicpd.org/download/mpd/0.13/mpd$(mpd-version:%=-%).tar.xz

CONFIG_MM_GMRENDER_SP:=y
gmrender-resurrect-version:=git
subproject-$(CONFIG_MM_GMRENDER_SP):=gmrender-resurrect
gmrender-resurrect-git:=https://github.com/hzeller/gmrender-resurrect.git
