linux-fusion-version=9.0.0
subproject-$(CONFIG_LINUX_FUSION)+=linux-fusion
linux-fusion-git=git://git.directfb.org/git/directfb/core/linux-fusion.git
linux-fusion-url=http://directfb.org/downloads/Core/linux-fusion/linux-fusion-$(linux-fusion-version).tar.gz
linux-fusion-mkconfig=$(src)/config/linux-fusion.mk

