subdir-y+=$(src)/tree $(src)/libc $(src)/base $(src)/init

subdir-y+=$(src)/framework/filecompressor
subdir-y+=$(src)/framework/fileparser
subdir-y+=$(src)/framework/ipc

subdir-y+=$(src)/lowlevel

subdir-y+=$(src)/framework

subdir-y+=$(src)/disk

subdir-y+=$(src)/server

subdir-y+=$(src)/lowlevel/graphics

subdir-y+=$(src)/dev

