subdir-y+=$(src)/filecompressor

subdir-y+=$(src)/fileparser

subdir-y+=$(src)/images

subdir-y+=$(src)/video

subdir-y+=$(src)/ipc

subdir-y+=$(src)/manager

subdir-y+=$(src)/dev

subdir-y+=$(src)/server
