busybox-version:=git
subproject-$(CONFIG_BUSYBOX)+=busybox
busybox-git:=git://git.busybox.net/busybox.git
busybox-defconfig:=$(src)/config/busybox_defconfig
busybox-makeflags=CONFIG_PREFIX=$(sprj-destdir)

subdir-$(CONFIG_GNU)+=gnu
