cups-version=1.7.0
subproject-$(CONFIG_CUPS)+=cups
cups-url="http://www.cups.org/software/$(cups-version)/cups-$(cups-version)-source.tar.bz2"

libsoup-version=2.45.3
libsoup-mainversion=2.45
#libsoup-version=git
subproject-$(CONFIG_LIBSOUP)+=libsoup
libsoup-url=https://download.gnome.org/sources/libsoup/$(libsoup-mainversion)/libsoup-$(libsoup-version).tar.xz
libsoup-git=git://git.gnome.org/libsoup

gssdp-version=0.14.6
gssdp-mainversion=0.14
subproject-$(CONFIG_GUPNP)+=gssdp
gssdp-url=https://download.gnome.org/sources/gupnp/$(gssdp-mainversion)/gssdp-$(gssdp-version).tar.xz
gssdp-git="git://git.gnome.org/gssdp.git"

gupnp-version=0.20.9
gupnp-mainversion=0.20
subproject-$(CONFIG_GUPNP)+=gupnp
gupnp-url=https://download.gnome.org/sources/gupnp/$(gupnp-mainversion)/gupnp-$(gupnp-version).tar.xz
gupnp-git="git://git.gnome.org/gupnp.git"

gupnp-dlna-version=0.10.2
gupnp-dlna-mainversion=0.10
subproject-$(CONFIG_GUPNP)+=gupnp-dlna
gupnp-dlna-url=https://download.gnome.org/sources/gupnp/$(gupnp-dlna-mainversion)/gupnp-dlna-$(gupnp-dlna-version).tar.xz
gupnp-dlna-git="git://git.gnome.org/gupnp-dlna.git"

