subdir-y+=$(src)/filecompressor

subdir-y+=$(src)/fileparser

subdir-y+=$(src)/images

subdir-y+=$(src)/video

ncurses-version:=$(CONFIG_FW_NCURSES_VERSION)
subproject-$(CONFIG_FW_NCURSES_SP)+=ncurses
ncurses-url:=http://ftp.gnu.org/pub/gnu/ncurses/ncurses-$(ncurses-version).tar.gz
