subdir-y+=$(src)/filecompressor

subdir-y+=$(src)/fileparser

subdir-y+=$(src)/images

subdir-y+=$(src)/video

subdir-y+=$(src)/ipc

ncurses-version:=5.9
subproject-$(CONFIG_NCURSES)+=ncurses
ncurses-url:=http://ftp.gnu.org/pub/gnu/ncurses/ncurses-$(ncurses-version).tar.gz
