maemo_flasher-version:=3.5_2.5.2.2
subproject-$(CONFIG_BOARD_BEAGLE)+=maemo_flasher
maemo_flasher-url:=http://tablets-dev.nokia.com/maemo-dev-env-downloads.php?f=maemo_flasher-3.5_2.5.2.2.tar.gz

riff-loader-communication-version:=git
subproject-$(CONFIG_BOARD_SNOWBALL)+=riff-loader-communication
riff-loader-communication-git:=https://github.com/igloocommunity/riff-loader-communication.git

riff-version:=git
subproject-$(CONFIG_BOARD_SNOWBALL)+=riff
riff-git:=https://github.com/igloocommunity/riff.git
