
subproject-$(CONFIG_TOOLS_MTD_UTILS)+=mtd-utils
mtd-utils-url:="git://git.infradead.org/mtd-utils.git"

subproject-$(CONFIG_TOOLS_NOKIA_FLASHER)+=maemo_flasher
maemo_flasher-url:=http://tablets-dev.nokia.com/maemo-dev-env-downloads.php?f=maemo_flasher-3.5_2.5.2.2.tar.gz

subproject-$(CONFIG_TOOLS_IGLOO_RIFF)+=riff

