
subproject-$(CONFIG_TOOLS_MTD_UTILS)+=mtd-utils
mtd-utils-git:="git://git.infradead.org/mtd-utils.git"

subproject-$(CONFIG_TOOLS_NOKIA_FLASHER)+=maemo_flasher
maemo_flasher-url:=http://tablets-dev.nokia.com/maemo-dev-env-downloads.php?f=maemo_flasher-3.5_2.5.2.2.tar.gz

subproject-$(CONFIG_TOOLS_IGLOO_RIFF)+=riff

fileutils-verion=4.0
download-y+=fileutils
fileutils-url=ftp://ftp.gnu.org/old-gnu/fileutils/fileutils-$(fileutils-verion).tar.gz
subdir-y+=$(src)/install
