subproject-$(CONFIG_BUSYBOX)+=busybox
busybox-git:=git://git.busybox.net/busybox.git
busybox-defconfig:=$(src)/config/busybox_defconfig
busybox-makeflags=CONFIG_PREFIX=$(objtree)/

subdir-$(CONFIG_GNU)+=gnu
