weston-version=$(CONFIG_WAYLAND_VERSION:"%"=%)
subproject-$(CONFIG_WESTON)+=weston
weston-url="http://wayland.freedesktop.org/releases/weston-$(weston-version).tar.xz"
weston-git="git://anongit.freedesktop.org/wayland/weston.git"
weston-mkconfig=graphics/system/config/wayland.mk

